# Generated by Django 3.0 on 2020-10-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookBlog', '0005_auto_20201015_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.RemoveField(
            model_name='post',
            name='book',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='ContCreator',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
